{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easyacc",
    "module": "tbmq",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tbmq-2.2.3.jar",
          "url": "tbmq-2.2.3.jar",
          "size": 884223,
          "sha512": "52bba03bd59c43aad89545c1be8c0ab94ae03c50c8854a5751c219fbff8727d1ae448130dfab4ed75a6bd7c1883c2813085061389e95221b71b8f4477e6fd25a",
          "sha256": "d569af506778a966eec010bba995b1eab1b2e6e6e09b23918f83c2be6fc20e84",
          "sha1": "a248b60b4a76a2ea61e2aaa42d69cd026a95fd2c",
          "md5": "216c2b7975d635643ede17ea8445562c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.gsonfire",
          "module": "gson-fire",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "tbmq-2.2.3.jar",
          "url": "tbmq-2.2.3.jar",
          "size": 884223,
          "sha512": "52bba03bd59c43aad89545c1be8c0ab94ae03c50c8854a5751c219fbff8727d1ae448130dfab4ed75a6bd7c1883c2813085061389e95221b71b8f4477e6fd25a",
          "sha256": "d569af506778a966eec010bba995b1eab1b2e6e6e09b23918f83c2be6fc20e84",
          "sha1": "a248b60b4a76a2ea61e2aaa42d69cd026a95fd2c",
          "md5": "216c2b7975d635643ede17ea8445562c"
        }
      ]
    }
  ]
}
