{
  "formatVersion": "1.1",
  "component": {
    "group": "com.amazon",
    "module": "spapi",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "spapi-1.3.2.jar",
          "url": "spapi-1.3.2.jar",
          "size": 2240704,
          "sha512": "1b3a791b7177120bd5982a608b05888dc69233b17ce2c612c040ee9594956262edd50624667b8e5a1c13d6ef436336235e65d07c4e462bf7f071874450d88b08",
          "sha256": "a20f840511fa37e1b63f546f3e3d01d134b4cbf859621a7c39e176434b476ec5",
          "sha1": "fd61c81866eb1e1d0121322f09f01b8ccddcc5a6",
          "md5": "33dc172070977fd44e2879002d3ce7ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-signer",
          "version": {
            "requires": "1.11.610"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-sts",
          "version": {
            "requires": "1.11.236"
          }
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-annotations",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp",
          "module": "okhttp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.squareup.okhttp",
          "module": "logging-interceptor",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "io.gsonfire",
          "module": "gson-fire",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "spapi-1.3.2.jar",
          "url": "spapi-1.3.2.jar",
          "size": 2240704,
          "sha512": "1b3a791b7177120bd5982a608b05888dc69233b17ce2c612c040ee9594956262edd50624667b8e5a1c13d6ef436336235e65d07c4e462bf7f071874450d88b08",
          "sha256": "a20f840511fa37e1b63f546f3e3d01d134b4cbf859621a7c39e176434b476ec5",
          "sha1": "fd61c81866eb1e1d0121322f09f01b8ccddcc5a6",
          "md5": "33dc172070977fd44e2879002d3ce7ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spapi-1.3.2-sources.jar",
          "url": "spapi-1.3.2-sources.jar",
          "size": 1249000,
          "sha512": "a7a87cad3456d59ef8e3d440762fea49f937a3c6c5f50e181c9a4ad34cd110bafba8198dbfa057aecf25f0d46a4b7b7e6f3e1b7904c1ebb50e7b234552e26490",
          "sha256": "8a3b07bb5bdba5ea9615306e3896fe75429102433623bab5b8730378a11dd810",
          "sha1": "de7ce171c4584de537985a6bd9a5c121000fe1f4",
          "md5": "a6f65c29e4ecb7e11affe17cbc1fbea4"
        }
      ]
    }
  ]
}
