{
  "formatVersion": "1.1",
  "component": {
    "group": "com.amazon",
    "module": "spapi",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "spapi-1.3.1.jar",
          "url": "spapi-1.3.1.jar",
          "size": 2240704,
          "sha512": "bee73312b212964b2948302c6733d3caa36ea81dc66c553730fe89a73c280a98ff8c33f7851784f7884e3b14b43126415ccd1373eb89fae3279f1b8c4240b0df",
          "sha256": "73b25fc24c9f3c56befe91fc5857bd6df5bb5fb1c0b7695dc825832284389a36",
          "sha1": "6088714ac0fb4838f28d2136228601603de56465",
          "md5": "7d096cea0de44f99c425967060021e74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-signer",
          "version": {
            "requires": "1.11.610"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-sts",
          "version": {
            "requires": "1.11.236"
          }
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-annotations",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp",
          "module": "okhttp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.squareup.okhttp",
          "module": "logging-interceptor",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "io.gsonfire",
          "module": "gson-fire",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "spapi-1.3.1.jar",
          "url": "spapi-1.3.1.jar",
          "size": 2240704,
          "sha512": "bee73312b212964b2948302c6733d3caa36ea81dc66c553730fe89a73c280a98ff8c33f7851784f7884e3b14b43126415ccd1373eb89fae3279f1b8c4240b0df",
          "sha256": "73b25fc24c9f3c56befe91fc5857bd6df5bb5fb1c0b7695dc825832284389a36",
          "sha1": "6088714ac0fb4838f28d2136228601603de56465",
          "md5": "7d096cea0de44f99c425967060021e74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spapi-1.3.1-sources.jar",
          "url": "spapi-1.3.1-sources.jar",
          "size": 1318982,
          "sha512": "a48f0aef158a009b8a881f6ada2b034267282b32fd63f509ebf6fc0f774f9b0dcf6cf5a2b51a04ddae97725d842d4cd5f386a9f6b6ae1ee1a102bbc73641235b",
          "sha256": "28c6e6ff8bb2c75fff534e6c629ea00e81c3849ad6052b901974e3e4a175f883",
          "sha1": "ebf7fcc7e1c08b5b663ed7d1d9903ca1bd9c4987",
          "md5": "2cc7dbae36e3d01c96befd844e24d941"
        }
      ]
    }
  ]
}
